version: '3.8'

services:
  lander:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/opt/lander
    restart: always
    command: npm start

